--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VapmPMMP
projects:
  VapmPMMP:
    model: virion
    type: library
    lint:
      phpstan: false
      syntaxError: false
...
