---
branches:
- main
projects:
  LibVapmPMMP:
    model: virion
    type: library
    lint:
      closeTag: false
      directStdout: false
      nonPsr: false
      syntaxError: false
      phpstan: false
    includeDirs:
      vendor: vendor
...
